name: google_maps_markerclusterer
description: Creates and manages per-zoom-level clusters for large amounts of markers.
version: 0.2.0
homepage: https://github.com/reyerstudio/google-maps-markerclusterer
author: Stéphane Este-Gracias <sestegra@gmail.com>

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  google_maps: ^4.0.0
  js_wrapping: ^0.6.0

dev_dependencies:
  build_runner: ^1.10.13
  build_web_compilers: ^2.16.0
  dart_style: ^1.3.11
  html: ^0.14.0+4
  js_wrapping_generator: ^0.6.0

# dependency_overrides:
#   google_maps:
#     git:
#       url: https://github.com/a14n/dart-google-maps
#       ref: master
#   js_wrapping:
#     git:
#       url: https://github.com/a14n/dart-js-wrapping.git
#       ref: master
#       path: js_wrapping
#   js_wrapping_generator:
#     git:
#       url: https://github.com/a14n/dart-js-wrapping.git
#       ref: master
#       path: js_wrapping_generator
